name: Golang Quality Pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'README.md'
      - '.goreleaser.yml'
  pull_request:
    types: [ opened, synchronize ]

jobs:

  build:
    name: Go Quality Inspection
    runs-on: ubuntu-latest
    steps:

    - name: Setting up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go
    
    - name: Setting up Go artifact cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Configure git for private modules
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git config --global url."https://alexbhr:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Getting dependencies...
      run: |
        go get -v -t -d ./...

    - name: Vetting code...
      run: go vet ./zotapay/

    - name: Testing code...
      run: go test -coverprofile=coverage.txt -covermode=atomic ./zotapay/

    - name: Uploading test coverage to Codecov...
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
