name: Go Matrix Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'examples/**'
      - 'README.md'
      - '.goreleaser.yml'
  pull_request:
    types: [ opened, synchronize ]

jobs:
  test:
    name: Matrix
    strategy:
      matrix:
        go-version: [ '1.20', '1.21', '1.22']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run tests
      run: go test ./zota/
